substitutions:
  friendlyname: Garage
esphome:
  name: garage-door-sensor
  project:
    name: psyciknz.garage-sensor
    version: "2.0.0"
  comment: "Garage door reed sensor and cover"

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:

mqtt:
  broker: !secret mqtt_ip
  #username: !secret mosquitto_username
  #password: !secret mosquitto_password
  topic_prefix: !secret mqtt_prefix

ota:
  platform: esphome
  password: "42e5b4b437dee84506bdcdc5f09658d7"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: !secret wifi_network

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Garage-Sensor Fallback Hotspot"
    password: "cv6hRjgELZF4"

captive_portal:


binary_sensor:
  - platform: gpio
    pin:
     number: D2
     mode: INPUT_PULLUP
     inverted: True
    id: contact
    name: 'Door Sensor'
    device_class: garage_door

  - platform: status
    name: "${friendlyname} Sensor Status"

button:
  - platform: restart
    name: ${friendlyname}  Reboot
    
  - platform: safe_mode
    name: ${friendlyname}  Safe Mode

sensor:
  - platform: uptime
    name: "${friendlyname} Uptime"
    disabled_by_default: true

  - platform: wifi_signal
    name: "${friendlyname} WiFi Signal"
    update_interval: 60s

cover:
  - platform: template
    device_class: garage
    name: "${friendlyname}"
    lambda: "return id(contact).state ? COVER_OPEN : COVER_CLOSED;"
    open_action:
      mqtt.publish:
        topic: "paradox/control/outputs/Garage_Door"
        payload: "pulse"
    close_action:
      mqtt.publish:
        topic: "paradox/control/outputs/Garage_Door"
        payload: "pulse"
