esphome:
  name: temperature-sensor

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "2f6e5dfff285a1a45af0136694359ddb"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Temperature-Sensor"
    password: "zMN5RdIdwixo"

captive_portal:
    